FROM alpine:3.7

RUN apk update && apk upgrade
RUN apk --update add \
  openssh git build-base libffi libffi-dev \
  ruby ruby-dev ruby-rake ruby-bundler

# RUN git clone https://github.com/daddygongon/my_help.git
COPY . ~/my_help
WORKDIR ~/my_help

RUN bundle update
RUN bundle exec exe/my_help -m && rake install:local
