#!/usr/bin/env ruby
require 'specific_help'
if ENV['LANG'] == "C" then
  help_file = File.join(ENV['HOME'],'.my_help','curriculum_help_e.yml')
else
  help_file = File.join(ENV['HOME'],'.my_help','curriculum_help.yml')
end
SpecificHelp::Command.run(help_file, ARGV)
