#!/usr/bin/env ruby
require 'specific_help_opt'
require 'specific_help_thor'
ENV['HELP_NAME']='umeda_help'
help_file = File.join(ENV['HOME'],'.my_help','umeda_help')
SpecificHelp::Command.start(ARGV)
SpecificHelpOpt::Command.run(help_file, ARGV)
