#+STARTUP: indent nolineimages

#+TITLE: めも

* 8/30
- ログを残す
- rbenv 2.4.3がなかった．`rm -rf ~/.rbenv`してしまったけど，消えなかった？意味なし．
`rbenv install -l`でinstallできるやつ探す．なかったから，`brew upgrade ruby-build`した．
`rbenv install -v 2.4.3`でinstall. 
- my_helpの方でrm -rfしてしまったからやばいかも．
- CoC:設定より既約

* 9/13
emacsでのUndo方法
- C-x u

本を渡されたので読む

単語や内容が重複した文章はダメ．
- はじめに．とは何か
研究内容．内容にあるwordを詳しく解説する．
学習管理とは？

起承転結

latexでは"_"が数式と勘違いしてしまうため，普通の表記にするには"\_"を使用する．
e.g.)my\_help

STARTUP: indent nolineimagesでorg-modeのindentされたやつになる．

* 卒論
- abst作る．パワポも．
テンプレがgrad_research/memebers/daddygongon/mid-term先生のとこにある．
emacs texTemolate.texで開く．open texTemplateでPDFとして開くハズ．．．(type set)
dvipdfmx ~.texでPDFに．texを２回まわして参照がちゃんとなるように参照解決する．
- 参考文献の書き方. 正式名称，著者，出版社，出版日を記述する．
- CMS: コンテンツ管理システム(Content Management System)，hikiなど．．．




| リスト | 項目 |
|--------+------|
|        |      |
|--------+------|
|        |      |

* 内容(下書き)
- コンセプト
my_help自体は，TODOファイルやmemoである．org-modeを利用しているので，長文やlatex，htmlにも対応している．
my_helpにemacsのキーバインド(振る舞い)を書くことによってBMSとなる．
私たちはノートにmemoをするが，無くしてしまうorどこにやったか分からなくなる．->my_helpを使うとそれがなくなる．
いつもwebで同じことを検索している．jupyternotebookの使い方とか，org-modeの使い方とか．

- 人間の脳が知識を何かの拍子に思い出す，キーワードが手がかりとなって違う分類，別の階層の記憶，知識を思い出す様に，システム上でも同じことができるシステム．人間の脳において知識が分類され，階層に分けられている(と仮定して)様に，コンピュータの中でも分類化，階層化された知識を直交補空間的に知識を呼び出すことを可能にするtool.

- my_helpに共有するシステムをのせると強制することができる．
BMS: 振る舞い管理システム(Behavior Management System)，Githubなど．．．

- something...
emacsのMarkdownであるorg-modeを利用．
org-modeで作成した文章はemacs以外でも利用できる．例えば，githubでは.mdと同じ様に.orgに対応している．また，org-modeのexport機能を利用すればHTMLやLaTexなど様々なフォーマットに変換可能．(https://qiita.com/dwarfJP/items/594a8d4b0ac6d248d1e4)
my_helpを使うにあたり，emacsとorg-modeの使い方をmasterしなければならない．
CUI/CLIのようにterminal上で動かす．
commandで呼び出すとすぐに起動する．


- 振る舞い
terminal上でmy_help file名と打つと起動する．
new :: 作成
edit :: 内容編集
delete :: 削除

TODOとして使うとき，DONEのやつはarchive(書庫)に入れる．いらなくなったから．

** アクティブラーニング
- 今の日本の教育ではあまり馴染みがない．
テキストや教授者から知識を得るのではなく，自らも参加者になって知識を共有(?)する．
- AM(acquisition metaphor)
- PM(participation metaphor): 学習あるいは学習者は参加者．学会活動もこれ．研究者が学会で認められるということは，その分野での用語を使って参加者とコミュニケーションを取れることであり．．．
  論文集を出すことや初心者向けのテキストを書いたりする活動も学習支援のひとつ．

|                 | acquisition metaphor         | participation metaphor    |   
|-----------------+------------------------------+---------------------------|
| 学習目標        | 個々を豊かにする             | 共同体の構築              |   
|-----------------+------------------------------+---------------------------|
| 学習とは？      | 何かを獲得する(acquisition)) | 参加者(participant)となる |   
|-----------------+------------------------------+---------------------------|    
| 学習者(student) | 受容者(消費者)，再構築者　   | 周辺にいる参加者，徒弟    |   
|-----------------+------------------------------+---------------------------|
| 教授者(teacher) | 供給者，まとめ役，媒介者     | 実践や論考の修得者        |   
|                 |                              |                           |   
|-----------------+------------------------------+---------------------------|
| 知識，概念      | 資産，所有物，一般商品       | 実践，論考，活動の一側面  |   
|                 | (個人のあるいは公共の)       |                           |   
|-----------------+------------------------------+---------------------------|
| 知るとは        | 持つ，所有すること           | 所属する，参加する，      |   
|                 |                              | コミュニケートすること    |   
|-----------------+------------------------------+---------------------------| 


*** 内世界，外世界
- 内世界は自分の中の知識

- 外世界はテキストや論文などの知識      

  
* 追加
list :: list all helps, specific HELP, or item

** my_helpの内容
- 知識
- 学習
- 進捗管理(これから) or Thorへの書き換え

** my_helpが使える　とは
touch typeができる．
editorのemacsが使える．
さらにMarkdownのorg-modeが使える．


** my_helpnのversionの上げ方
gem install my_help

** errorの対処法
my_help edit tomochan_diaryと打つと
file /Users/yamadatomoko/.my_help/tomochan_diary.org does not exits in /Users/yamadatomoko/.my_help.
init tomochan_diary first.
とエラーが出た．
my_helpのversionをあげたら解決．解決内容はdiffをとる．

my_help list ファイル名でそのファイル内のitemを表示する．
拡張子をつけると
error: No such file or directory @ rb_sysopen - /Users/yamadatomoko/.my_help/tomochan_diary.org.org
となり，.org.orgの様におかしなことが起こる．

 my_help list tomochan_diary でlist表示．
   -男, 男もすなる日記といふものを，女もしてみむとてするなり．: 男もすなる日記といふものを，女もしてみむとてするなり．
   -2, 2018/8/31      : 2018/8/31
     , 2018/9/1       : 2018/9/1
     , 2018/9/2       : 2018/9/2
     , 2018/9/4       : 2018/9/4
     , 2018/9/5       : 2018/9/5
     , 2018/9/6       : 2018/9/6
     , 2018/9/13      : 2018/9/13
itemの表示がされた．

** 今後の課題
my_helpを共有できる様にする．
- 進捗管理を行うことにより，学習の強制ができる．
(もしくはThorへの書き換え.コマンドラインツールを作るためのgem．Rakeより引数受け渡しが簡単．)


* はじめに
アクティブラーニングを実現するシステムを構築するためにmy_helpというmemoソフトを開発する．
アクティブラーニングとは，共同体に参加することによって知識を得る

* gem 
gemをリリースする前にlocal環境で試すcommand．同じディレクトリで打たないと反応しない．
rake install:local
